/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DOA.ClienteCONEC;
import Model.Cliente;
import Model.Prods_Comprados;
import Model.SenhaCompara;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Telas.Login;
import TelasUtil.LimitaCaracteres;
import javax.swing.JOptionPane;
import Telas.Inicial;

/**
 *
 * @author guilh
 */
public class Conta extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Conta() {
        initComponents();
        
        //Limitaações doque pode ser digitado nos campos
        txtNome.setDocument(new LimitaCaracteres(50, LimitaCaracteres.TipoEntrada.NOME));
        txtEndereco.setDocument(new LimitaCaracteres(100, LimitaCaracteres.TipoEntrada.ENDERECO));
        txtCpf.setDocument(new LimitaCaracteres(11, LimitaCaracteres.TipoEntrada.CPF));
        txtTelefone.setDocument(new LimitaCaracteres(20, LimitaCaracteres.TipoEntrada.TELEFONE));
        txtSenhacomando.setDocument(new LimitaCaracteres(12, LimitaCaracteres.TipoEntrada.SENHA));
        txtEmail.setDocument(new LimitaCaracteres(50, LimitaCaracteres.TipoEntrada.EMAIL));
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCONTA = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenhacomando = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelCliente = new javax.swing.JTable();
        btnCarregar = new javax.swing.JButton();
        btnAltera = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Conta");
        jButton4.setToolTipText("");
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Novidades");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Conta");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1004, 562));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LogoBS_semFundo1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        btnCONTA.setBackground(new java.awt.Color(0, 0, 0));
        btnCONTA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCONTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/88-885453_login-white-on-clear-user-icon.png"))); // NOI18N
        btnCONTA.setText(" Conta");
        btnCONTA.setToolTipText("");
        btnCONTA.setBorderPainted(false);
        btnCONTA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCONTA.setEnabled(false);
        btnCONTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCONTAActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/the-white-shopping-bag-icon-1.png"))); // NOI18N
        jButton5.setText(" Compras");
        jButton5.setToolTipText("");
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carrinho.png"))); // NOI18N
        jButton6.setText(" Carrinho");
        jButton6.setToolTipText("");
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cupom.png"))); // NOI18N
        jButton7.setText(" Cupons");
        jButton7.setToolTipText("");
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logout.png"))); // NOI18N
        jButton9.setText(" Sair");
        jButton9.setToolTipText("");
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(btnCONTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCONTA)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 930, 76);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INFORMAÇÕES DA SUA CONTA");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(400, 90, 174, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Digite sua senha novamente  para alterar ou excluir:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(210, 130, 285, 16);

        txtSenhacomando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhacomandoActionPerformed(evt);
            }
        });
        jPanel3.add(txtSenhacomando);
        txtSenhacomando.setBounds(500, 130, 213, 24);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(340, 170, 37, 27);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(210, 200, 35, 24);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Endereço:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(210, 270, 56, 24);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefone:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(480, 240, 51, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CPF:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(210, 240, 27, 16);
        jPanel3.add(txtEndereco);
        txtEndereco.setBounds(270, 270, 492, 24);
        jPanel3.add(txtEmail);
        txtEmail.setBounds(250, 200, 507, 24);
        jPanel3.add(txtNome);
        txtNome.setBounds(390, 170, 369, 24);

        jTextField5.setText("jTextField2");
        jPanel3.add(jTextField5);
        jTextField5.setBounds(108, 251, 74, 0);
        jPanel3.add(txtTelefone);
        txtTelefone.setBounds(540, 230, 218, 24);
        jPanel3.add(txtCpf);
        txtCpf.setBounds(250, 230, 220, 24);

        btnOK.setBackground(new java.awt.Color(0, 0, 0));
        btnOK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.setBorderPainted(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel3.add(btnOK);
        btnOK.setBounds(730, 130, 50, 28);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tabelCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID","Nome", "Email", "Endereço","Telefone","CPF"
            }
        ));
        jScrollPane1.setViewportView(tabelCliente);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(210, 350, 554, 45);

        btnCarregar.setBackground(new java.awt.Color(0, 0, 0));
        btnCarregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCarregar.setForeground(new java.awt.Color(255, 255, 255));
        btnCarregar.setText("CARREGAR INFORMAÇÕES");
        btnCarregar.setBorderPainted(false);
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCarregar);
        btnCarregar.setBounds(370, 430, 240, 28);

        btnAltera.setBackground(new java.awt.Color(0, 0, 0));
        btnAltera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAltera.setForeground(new java.awt.Color(255, 255, 255));
        btnAltera.setText("ALTERAR");
        btnAltera.setBorderPainted(false);
        btnAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraActionPerformed(evt);
            }
        });
        jPanel3.add(btnAltera);
        btnAltera.setBounds(370, 310, 100, 28);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(210, 170, 15, 20);

        txtId.setEditable(false);
        jPanel3.add(txtId);
        txtId.setBounds(230, 170, 97, 24);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Clique na respectiva linha para selecionar");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(380, 400, 231, 16);

        btnExcluir.setBackground(new java.awt.Color(0, 0, 0));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setBorderPainted(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(btnExcluir);
        btnExcluir.setBounds(500, 310, 94, 28);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DETRAS.png"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(0, 60, 930, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Compras a = new Compras();
        this.dispose();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Carrinho b = new Carrinho();
        this.dispose();
        b.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Cupons c = new Cupons();
        this.dispose();
        c.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Inicial x = new Inicial();
        this.dispose();
        x.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnCONTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCONTAActionPerformed
               
        Conta u = new Conta();
        this.dispose();
        u.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCONTAActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Principal t = new Principal();
        this.dispose();
        t.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
       
        SenhaCompara novo = new SenhaCompara();
        novo.setSenha(txtSenhacomando.getText());
        
       
        //Comparção de senhas digitadas mo login e no novo campo
        
        if( novo.getSenha().equals(Login.txtSenha.getText())){
            
             listavaloresdaconta(txtSenhacomando.getText());
            
        }else{
            JOptionPane.showMessageDialog(null, "Não é sua senha");
            
        }
        
        
        
       
        
        
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void txtSenhacomandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhacomandoActionPerformed
        
    }//GEN-LAST:event_txtSenhacomandoActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
       carregarcampos();
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraActionPerformed
       
       verificacoes();
    }//GEN-LAST:event_btnAlteraActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente excluir essa conta?") == JOptionPane.YES_OPTION){
            
            excluircliente();
            JOptionPane.showMessageDialog(null, "Conta excluida");
            Inicial t = new Inicial();
            this.dispose();
            t.setVisible(true);
            
        }else{
              
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltera;
    private javax.swing.JButton btnCONTA;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tabelCliente;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenhacomando;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void listavaloresdaconta(String Senha){
        
        try {
          
            ClienteCONEC novo = new ClienteCONEC();
            
            DefaultTableModel model = (DefaultTableModel) tabelCliente.getModel();
            model.setNumRows(0);
            
            //Joga o objeto num array para poder mostra-lo numa tabela
           
            ArrayList<Cliente> novalista = novo.setacadastros(Senha);
            

                for(int num = 0; num < novalista.size(); num++){

                    model.addRow(new Object[]{
                        //seta as informaçoes desejadas em cada coluna da tabela

                        novalista.get(num).getId(),
                        novalista.get(num).getNome(),
                        novalista.get(num).getEmail(),
                        novalista.get(num).getEndereco(),                  
                        novalista.get(num).getTelefone(),
                        novalista.get(num).getCpf()


                    });
                    
                }
            
        
            
            
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lista valores" + e.getMessage());
        }
        
    }


    private void carregarcampos(){
    
        int setar = tabelCliente.getSelectedRow();
        
        //Pega os valores da tabela na linha selecionada e joga nos campos de texto
        txtId.setText(tabelCliente.getModel().getValueAt(setar, 0).toString());
        txtNome.setText(tabelCliente.getModel().getValueAt(setar, 1).toString());
        txtEmail.setText(tabelCliente.getModel().getValueAt(setar, 2).toString());
        txtEndereco.setText(tabelCliente.getModel().getValueAt(setar, 3).toString());     
        txtTelefone.setText(tabelCliente.getModel().getValueAt(setar, 4).toString());
        txtCpf.setText(tabelCliente.getModel().getValueAt(setar, 5).toString());
        
    }
       
   
    private void AlterarCadastro(){
        
        Cliente novo = new Cliente(0, "", "", "", "", "", 0);
        
        //pego os dados da interface
        novo.setNome(txtNome.getText());
        novo.setEmail(txtEmail.getText());
        novo.setEndereco(txtEndereco.getText());
        novo.setTelefone(txtTelefone.getText());
        novo.setCpf(txtCpf.getText());
        
        //Novo objeto da classe de conexão para alterar os dados
        ClienteCONEC nou = new ClienteCONEC();
        nou.AlterarCadastro(novo, txtSenhacomando.getText());
        
        
    }
    
    public void excluircliente(){
        
        String senha = txtSenhacomando.getText();
        //Exlui o cliente a partir da senha digitada
         Cliente novo = new Cliente(0, "", "", "", "", "", 0);
         novo.setSenha(senha);
         
         ClienteCONEC conec = new ClienteCONEC();
         
         conec.excluirCliente(novo);

        
    }
    
    private void verificacoes(){
        
         //Deixando os campos obrigatórios
        if(txtNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Nome é obrigatório, favor preencher", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txtEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Email é obrigatório, favor preencher", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txtCpf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo CPF é obrigatório, favor preencher", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txtTelefone.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Telefone é obrigatório, favor preencher", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txtEndereco.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Endereço é obrigatório, favor preencher", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(txtCpf.getText().isEmpty() || txtEmail.getText().isEmpty() ||txtEndereco.getText().isEmpty() ||txtNome.getText().isEmpty() ||txtTelefone.getText().isEmpty() ){
        //Botao faz a alteração e ja mostra na tabela
        }else{
        listavaloresdaconta(txtSenhacomando.getText());
        AlterarCadastro();    
        JOptionPane.showMessageDialog(null, "Alterações feitas com sucesso!");
        
        }
        
        
    }
}

