/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DOA.CupomCONEC;
import DOA.Prods_CompradosCONEC;
import Model.Boleto;
import Model.Credito;
import Model.Cupom;
import Model.Debito;
import Model.Pix;
import Model.Prods_Comprados;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import TelasUtil.UtilPagamento;
import Telas.Carrinho;
/**
 *
 * @author guilh
 */
public class Pagamento extends javax.swing.JFrame {

    /**
     * Creates new form Pagamento
     */
    public Pagamento() {
        initComponents();
        txtsubtpagamnento.setText(Carrinho.txtSoma.getText());
        txtdescontocupom.setText("0.0");
        txtimposto.setText("12%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combMetodo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrazopadrao = new javax.swing.JRadioButton();
        txtprazo10 = new javax.swing.JRadioButton();
        txtprazo20 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCupom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsubtpagamnento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttotalfinal = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtimposto = new javax.swing.JTextField();
        btnAcaoCupom = new javax.swing.JButton();
        txtdescontocupom = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCONTA = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tala Pagamento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Forma de Pagamento:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(24, 17, 149, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escolha a forma de pagamento dentre as opções, e não se esqueça de olhar a tabela de descontos!");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(64, 43, 517, 16);

        combMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "PIX", "Boleto", "Cartão de Débito", "Cartão de Crédito" }));
        combMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combMetodoActionPerformed(evt);
            }
        });
        jPanel1.add(combMetodo);
        combMetodo.setBounds(24, 77, 282, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Aceitamos:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(780, 40, 74, 20);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("PIX - 8%\nBoleto - 5%\nCartão de Débito - 7%\nCartão de Crédito - 0%");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(24, 125, 370, 100);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Frete:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(24, 251, 38, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Escolha quando deseja receber sua entrega:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 280, 229, 16);

        txtPrazopadrao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPrazopadrao.setForeground(new java.awt.Color(255, 255, 255));
        txtPrazopadrao.setText("Entrega no prazo padrão (30 dias): +0%");
        jPanel1.add(txtPrazopadrao);
        txtPrazopadrao.setBounds(63, 305, 238, 20);

        txtprazo10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtprazo10.setForeground(new java.awt.Color(255, 255, 255));
        txtprazo10.setText("Entrega em 10 dias: +15%");
        txtprazo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprazo10ActionPerformed(evt);
            }
        });
        jPanel1.add(txtprazo10);
        txtprazo10.setBounds(63, 339, 166, 20);

        txtprazo20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtprazo20.setForeground(new java.awt.Color(255, 255, 255));
        txtprazo20.setText("Entrega em 20 dias: + 10%");
        txtprazo20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprazo20ActionPerformed(evt);
            }
        });
        jPanel1.add(txtprazo20);
        txtprazo20.setBounds(63, 373, 169, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cupons:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(410, 260, 53, 20);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Caso tenha algum cupom, informe seu código para resgatá-lo.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(410, 290, 331, 16);
        jPanel1.add(txtCupom);
        txtCupom.setBounds(410, 320, 284, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Impostos:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 80, 65, 20);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Valor referente ao imposto.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 110, 250, 16);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Subtotal:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(840, 330, 50, 16);

        txtsubtpagamnento.setEditable(false);
        txtsubtpagamnento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtpagamnentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtsubtpagamnento);
        txtsubtpagamnento.setBounds(910, 320, 196, 22);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(840, 360, 31, 16);

        txttotalfinal.setEditable(false);
        txttotalfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalfinalActionPerformed(evt);
            }
        });
        jPanel1.add(txttotalfinal);
        txttotalfinal.setBounds(910, 360, 196, 22);

        btnCalcular.setBackground(new java.awt.Color(0, 0, 0));
        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.setBorderPainted(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular);
        btnCalcular.setBounds(1130, 320, 110, 26);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pix.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1210, 90, 90, 69);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/boleto.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1110, 90, 90, 69);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mastercard.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(970, 90, 125, 69);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/visa.jpg"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(820, 90, 143, 72);

        txtimposto.setEditable(false);
        jPanel1.add(txtimposto);
        txtimposto.setBounds(460, 140, 284, 22);

        btnAcaoCupom.setText("OK");
        btnAcaoCupom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoCupomActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcaoCupom);
        btnAcaoCupom.setBounds(700, 320, 55, 22);

        txtdescontocupom.setEditable(false);
        jPanel1.add(txtdescontocupom);
        txtdescontocupom.setBounds(490, 360, 121, 22);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DESCONTO:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(410, 360, 64, 16);

        btnPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPagar.setText("PAGAR");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagar);
        btnPagar.setBounds(1150, 360, 70, 28);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(659, 314, 0, 0);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MAIOR.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(0, -10, 1310, 450);

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LogoBS_semFundo1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        btnCONTA.setBackground(new java.awt.Color(0, 0, 0));
        btnCONTA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCONTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/88-885453_login-white-on-clear-user-icon.png"))); // NOI18N
        btnCONTA.setText(" Conta");
        btnCONTA.setToolTipText("");
        btnCONTA.setBorderPainted(false);
        btnCONTA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCONTA.setEnabled(false);
        btnCONTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCONTAActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/the-white-shopping-bag-icon-1.png"))); // NOI18N
        jButton5.setText(" Compras");
        jButton5.setToolTipText("");
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carrinho.png"))); // NOI18N
        jButton6.setText(" Carrinho");
        jButton6.setToolTipText("");
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cupom.png"))); // NOI18N
        jButton7.setText(" Cupons");
        jButton7.setToolTipText("");
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logout.png"))); // NOI18N
        jButton9.setText(" Sair");
        jButton9.setToolTipText("");
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCONTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCONTA)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1305, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Principal t = new Principal();
        this.dispose();
        t.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnCONTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCONTAActionPerformed

        Conta u = new Conta();
        this.dispose();
        u.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCONTAActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Compras a = new Compras();
        this.dispose();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Carrinho b = new Carrinho();
        this.dispose();
        b.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Cupons c = new Cupons();
        this.dispose();
        c.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Inicial x = new Inicial();
        this.dispose();
        x.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        cadastra_produto();
        JOptionPane.showMessageDialog(null,"Pagamento Confirmado!" +"\n"+"O pedido será enviado para seu endereço!");
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnAcaoCupomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoCupomActionPerformed

        cupom(Integer.parseInt(txtCupom.getText()));
    }//GEN-LAST:event_btnAcaoCupomActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        calcular();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtsubtpagamnentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtpagamnentoActionPerformed

    }//GEN-LAST:event_txtsubtpagamnentoActionPerformed

    private void txtprazo20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprazo20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprazo20ActionPerformed

    private void txtprazo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprazo10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprazo10ActionPerformed

    private void txttotalfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalfinalActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalfinalActionPerformed

    private void combMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combMetodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcaoCupom;
    private javax.swing.JButton btnCONTA;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> combMetodo;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtCupom;
    private javax.swing.JRadioButton txtPrazopadrao;
    private javax.swing.JTextField txtdescontocupom;
    private javax.swing.JTextField txtimposto;
    private javax.swing.JRadioButton txtprazo10;
    private javax.swing.JRadioButton txtprazo20;
    private javax.swing.JTextField txtsubtpagamnento;
    private javax.swing.JTextField txttotalfinal;
    // End of variables declaration//GEN-END:variables

        private void cupom(int x){
            //Autentifa a existencia do cupom digitado pelo cliente
            try{

               CupomCONEC cupom = new CupomCONEC();

               Cupom novo = cupom.AutentificarOCupom(x);

                if (novo == null){

                    JOptionPane.showMessageDialog(null, "Cupom não existe!");
                    txtdescontocupom.setText("0.0");
                } else {

                    Double e = novo.getValor();
                    txtdescontocupom.setText(e.toString());

                }


            }catch(Exception erro){
                JOptionPane.showMessageDialog(null,"Cupom " + erro.getMessage());

            }
        
            
            
        }
        
        
        private void cadastra_produto(){
            //Quando um cliente compra um produto esse é cadastrado em sua conta 
            if(!Carrinho.txtTitulo0.getText().isEmpty()){

                Prods_Comprados novo0 = new Prods_Comprados("","",0.0);
                novo0.setSenha(Login.txtSenha.getText());
                novo0.setTitulo(Carrinho.txtTitulo0.getText());
                novo0.setValor(Double.parseDouble(Carrinho.txtValor0.getText()));
                Prods_CompradosCONEC conecta0 = new Prods_CompradosCONEC();
                conecta0.CadastrarProds_comprados(novo0);
            }

            if(!Carrinho.txtTitulo1.getText().isEmpty()){

                Prods_Comprados novo1 = new Prods_Comprados("","",0.0);
                novo1.setSenha(Login.txtSenha.getText());
                novo1.setTitulo(Carrinho.txtTitulo1.getText());
                novo1.setValor(Double.parseDouble(Carrinho.txtValor1.getText()));
                Prods_CompradosCONEC conecta1 = new Prods_CompradosCONEC();
                conecta1.CadastrarProds_comprados(novo1);


            }

            if(!Carrinho.txtTitulo2.getText().isEmpty()){

                Prods_Comprados novo2 = new Prods_Comprados("","",0.0);
                novo2.setSenha(Login.txtSenha.getText());
                novo2.setTitulo(Carrinho.txtTitulo2.getText());
                novo2.setValor(Double.parseDouble(Carrinho.txtValor2.getText()));
                Prods_CompradosCONEC conecta2 = new Prods_CompradosCONEC();
                conecta2.CadastrarProds_comprados(novo2);

            }

            if(!Carrinho.txtTitulo3.getText().isEmpty()){

                Prods_Comprados novo3 = new Prods_Comprados("","",0.0);
                novo3.setSenha(Login.txtSenha.getText());
                novo3.setTitulo(Carrinho.txtTitulo3.getText());
                novo3.setValor(Double.parseDouble(Carrinho.txtValor3.getText()));
                Prods_CompradosCONEC conecta3 = new Prods_CompradosCONEC();
                conecta3.CadastrarProds_comprados(novo3);

            }

            if(!Carrinho.txtTitulo4.getText().isEmpty()){

                Prods_Comprados novo4 = new Prods_Comprados("","",0.0);
                novo4.setSenha(Login.txtSenha.getText());
                novo4.setTitulo(Carrinho.txtTitulo4.getText());
                novo4.setValor(Double.parseDouble(Carrinho.txtValor4.getText()));
                Prods_CompradosCONEC conecta4 = new Prods_CompradosCONEC();
                conecta4.CadastrarProds_comprados(novo4);

            }

            
        }
        
        private void calcular(){
            
                String decide ="";
                //Calculos referentes a descontos, parcelas e incrementos
            if(combMetodo.getSelectedItem() == "PIX" && txtPrazopadrao.isSelected()){
                decide = "PP";
                Pix novo = new Pix("");
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));
                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));

            }else if(combMetodo.getSelectedItem() == "PIX" && txtprazo20.isSelected()){
                decide = "P20";
                Pix novo = new Pix("");
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));     
                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));

            }else if(combMetodo.getSelectedItem() == "PIX" && txtprazo10.isSelected()){

                decide = "P10";
                Pix novo = new Pix("");
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));
                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));

            }else if(combMetodo.getSelectedItem() == "Boleto" && txtPrazopadrao.isSelected()){

                decide = "BP";
                Boleto novo = new Boleto("",null);
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));
                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));

            }else if(combMetodo.getSelectedItem() == "Boleto" && txtprazo20.isSelected()){

                decide = "B20";
                Boleto novo = new Boleto("",null);
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));         
                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));

            }else if(combMetodo.getSelectedItem() == "Boleto" && txtprazo10.isSelected()){

                decide = "B10";
                Boleto novo = new Boleto("",null);
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));  
                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));

            }else if(combMetodo.getSelectedItem() == "Cartão de débito" && txtPrazopadrao.isSelected()){

                decide = "CDP";
                Debito novo = new Debito("","",0,null);
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));
                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));

            }else if(combMetodo.getSelectedItem() == "Cartão de débito" && txtprazo20.isSelected()){

                decide = "CD20";
                Debito novo = new Debito("","",0,null);
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));
                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));
                
            }else if(combMetodo.getSelectedItem() == "Cartão de débito" && txtprazo10.isSelected()){

                decide = "CD10";
                Debito novo = new Debito("","",0,null);
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));

                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));
            }else if(combMetodo.getSelectedItem() == "Cartão de crédito" && txtPrazopadrao.isSelected()){

                decide = "CCP";
                Credito novo = new Credito("","",0,null,0);
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));

                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));
            }else if(combMetodo.getSelectedItem() == "Cartão de crédito" && txtprazo20.isSelected()){

                decide = "CC20";
                Credito novo = new Credito("","",0,null,0);
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));

               txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));
            }else if(combMetodo.getSelectedItem() == "Cartão de crédito" && txtprazo10.isSelected()){

                decide = "CC10";
                Credito novo = new Credito("","",0,null,0);
                Double t = novo.efetuarCompra(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));

                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));
            }else{

                Double t = UtilPagamento.paga(decide,Double.parseDouble(txtsubtpagamnento.getText()),Double.parseDouble(txtdescontocupom.getText()));

                txttotalfinal.setText(Double.toString(t).formatted("%.2f", t));
            }

        }
}
