/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import Model.Produto;
import DOA.ProdutosCONEC;
import javax.swing.JOptionPane;
import DOA.Conexao;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.ImageIcon;
/**
 *
 * @author guilh
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Principal() {
        initComponents();
        mostrarlivrosnaprincipal();
        txtDesc.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtpesquisar = new javax.swing.JTextField();
        LabelPesquisar = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        TxtAutor = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        txtCusto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        Imagem1 = new javax.swing.JLabel();
        txtnome1 = new javax.swing.JTextField();
        Imagem0 = new javax.swing.JLabel();
        txtpreco1 = new javax.swing.JTextField();
        Imagem2 = new javax.swing.JLabel();
        txtnome2 = new javax.swing.JTextField();
        txtpreco2 = new javax.swing.JTextField();
        Imagem4 = new javax.swing.JLabel();
        txtpreco5 = new javax.swing.JTextField();
        txtnome4 = new javax.swing.JTextField();
        txtpreco3 = new javax.swing.JTextField();
        Imagem3 = new javax.swing.JLabel();
        txtnome3 = new javax.swing.JTextField();
        txtpreco4 = new javax.swing.JTextField();
        Imagem5 = new javax.swing.JLabel();
        txtnome5 = new javax.swing.JTextField();
        btnCarrinho3 = new javax.swing.JButton();
        btnCarrinho4 = new javax.swing.JButton();
        btnCarrinho5 = new javax.swing.JButton();
        btnCarrinho2 = new javax.swing.JButton();
        btnCarrinho1 = new javax.swing.JButton();
        btnCarrinho = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        Painel1 = new javax.swing.JPanel();
        txtnome6 = new javax.swing.JTextField();
        txtpreco6 = new javax.swing.JTextField();
        btnCarrinho6 = new javax.swing.JButton();
        Imagem6 = new javax.swing.JLabel();
        txtdesc6 = new javax.swing.JTextField();
        Painel2 = new javax.swing.JPanel();
        txtnome7 = new javax.swing.JTextField();
        txtpreco7 = new javax.swing.JTextField();
        btnCarrinho7 = new javax.swing.JButton();
        Imagem7 = new javax.swing.JLabel();
        txtdesc7 = new javax.swing.JTextField();
        Painel4 = new javax.swing.JPanel();
        txtnome8 = new javax.swing.JTextField();
        txtpreco8 = new javax.swing.JTextField();
        btnCarrinho8 = new javax.swing.JButton();
        Imagem8 = new javax.swing.JLabel();
        txtdesc8 = new javax.swing.JTextField();
        Painel7 = new javax.swing.JPanel();
        txtnome9 = new javax.swing.JTextField();
        txtpreco9 = new javax.swing.JTextField();
        btnCarrinho9 = new javax.swing.JButton();
        Imagem9 = new javax.swing.JLabel();
        txtdesc9 = new javax.swing.JTextField();
        Painel8 = new javax.swing.JPanel();
        txtnome10 = new javax.swing.JTextField();
        txtpreco10 = new javax.swing.JTextField();
        btnCarrinho10 = new javax.swing.JButton();
        Imagem10 = new javax.swing.JLabel();
        txtdesc10 = new javax.swing.JTextField();
        Painel9 = new javax.swing.JPanel();
        txtnome11 = new javax.swing.JTextField();
        txtpreco11 = new javax.swing.JTextField();
        btnCarrinho11 = new javax.swing.JButton();
        Imagem11 = new javax.swing.JLabel();
        txtdesc11 = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        txtdesc1 = new javax.swing.JTextField();
        txtdesc2 = new javax.swing.JTextField();
        txtdesc3 = new javax.swing.JTextField();
        txtdesc4 = new javax.swing.JTextField();
        txtdesc5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        painelImg = new javax.swing.JPanel();
        lbImagem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Conta");
        jButton4.setToolTipText("");
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Novidades");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1004, 562));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(125, 255, 232));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LogoBS_semFundo1.png"))); // NOI18N

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/88-885453_login-white-on-clear-user-icon.png"))); // NOI18N
        jButton3.setText(" Conta");
        jButton3.setToolTipText("");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/the-white-shopping-bag-icon-1.png"))); // NOI18N
        jButton5.setText(" Compras");
        jButton5.setToolTipText("");
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carrinho.png"))); // NOI18N
        jButton6.setText(" Carrinho");
        jButton6.setToolTipText("");
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cupom.png"))); // NOI18N
        jButton7.setText(" Cupons");
        jButton7.setToolTipText("");
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logout.png"))); // NOI18N
        jButton9.setText(" Sair");
        jButton9.setToolTipText("");
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 444, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 80));

        txtpesquisar.setDoubleBuffered(true);
        txtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarActionPerformed(evt);
            }
        });
        jPanel3.add(txtpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 1060, 30));

        LabelPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.png"))); // NOI18N
        LabelPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelPesquisarMouseClicked(evt);
            }
        });
        jPanel3.add(LabelPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtTitulo.setEditable(false);
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        jPanel3.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 310, -1));

        TxtAutor.setEditable(false);
        TxtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAutorActionPerformed(evt);
            }
        });
        jPanel3.add(TxtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, -1));

        txtEditora.setEditable(false);
        jPanel3.add(txtEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 130, -1));

        txtCusto.setEditable(false);
        jPanel3.add(txtCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel5.setBackground(new java.awt.Color(125, 255, 232));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Imagem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Imagem1.setPreferredSize(new java.awt.Dimension(138, 188));

        txtnome1.setEditable(false);
        txtnome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnome1ActionPerformed(evt);
            }
        });

        Imagem0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Imagem0.setPreferredSize(new java.awt.Dimension(138, 188));

        txtpreco1.setEditable(false);
        txtpreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreco1ActionPerformed(evt);
            }
        });

        Imagem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtnome2.setEditable(false);
        txtnome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnome2ActionPerformed(evt);
            }
        });

        txtpreco2.setEditable(false);
        txtpreco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreco2ActionPerformed(evt);
            }
        });

        Imagem4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtpreco5.setEditable(false);
        txtpreco5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreco5ActionPerformed(evt);
            }
        });

        txtnome4.setEditable(false);
        txtnome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnome4ActionPerformed(evt);
            }
        });

        txtpreco3.setEditable(false);

        Imagem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtnome3.setEditable(false);

        txtpreco4.setEditable(false);
        txtpreco4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreco4ActionPerformed(evt);
            }
        });

        Imagem5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtnome5.setEditable(false);
        txtnome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnome5ActionPerformed(evt);
            }
        });

        btnCarrinho3.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho3.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho3.setText("+CARRINHO");
        btnCarrinho3.setBorderPainted(false);
        btnCarrinho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho3ActionPerformed(evt);
            }
        });

        btnCarrinho4.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho4.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho4.setText("+CARRINHO");
        btnCarrinho4.setBorderPainted(false);
        btnCarrinho4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho4ActionPerformed(evt);
            }
        });

        btnCarrinho5.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho5.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho5.setText("+CARRINHO");
        btnCarrinho5.setBorderPainted(false);
        btnCarrinho5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho5ActionPerformed(evt);
            }
        });

        btnCarrinho2.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho2.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho2.setText("+CARRINHO");
        btnCarrinho2.setBorderPainted(false);
        btnCarrinho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho2ActionPerformed(evt);
            }
        });

        btnCarrinho1.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho1.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho1.setText("+CARRINHO");
        btnCarrinho1.setBorderPainted(false);
        btnCarrinho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho1ActionPerformed(evt);
            }
        });

        btnCarrinho.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho.setText("+CARRINHO");
        btnCarrinho.setBorderPainted(false);
        btnCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinhoActionPerformed(evt);
            }
        });

        txtNome.setEditable(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtpreco.setEditable(false);
        txtpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoActionPerformed(evt);
            }
        });

        Painel1.setBackground(new java.awt.Color(125, 255, 232));

        txtnome6.setEditable(false);

        txtpreco6.setEditable(false);

        btnCarrinho6.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho6.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho6.setText("+CARRINHO");
        btnCarrinho6.setBorderPainted(false);
        btnCarrinho6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho6ActionPerformed(evt);
            }
        });

        Imagem6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtdesc6.setEditable(false);

        javax.swing.GroupLayout Painel1Layout = new javax.swing.GroupLayout(Painel1);
        Painel1.setLayout(Painel1Layout);
        Painel1Layout.setHorizontalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel1Layout.createSequentialGroup()
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Imagem6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarrinho6, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnome6)
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpreco6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdesc6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Painel1Layout.setVerticalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addComponent(txtnome6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpreco6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc6))
                    .addComponent(Imagem6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCarrinho6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Painel2.setBackground(new java.awt.Color(125, 255, 232));

        txtnome7.setEditable(false);

        txtpreco7.setEditable(false);

        btnCarrinho7.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho7.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho7.setText("+CARRINHO");
        btnCarrinho7.setBorderPainted(false);
        btnCarrinho7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho7ActionPerformed(evt);
            }
        });

        Imagem7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtdesc7.setEditable(false);

        javax.swing.GroupLayout Painel2Layout = new javax.swing.GroupLayout(Painel2);
        Painel2.setLayout(Painel2Layout);
        Painel2Layout.setHorizontalGroup(
            Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCarrinho7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Imagem7, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpreco7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome7, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(txtdesc7))
                .addGap(413, 413, 413))
        );
        Painel2Layout.setVerticalGroup(
            Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel2Layout.createSequentialGroup()
                .addGroup(Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel2Layout.createSequentialGroup()
                        .addComponent(txtnome7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtpreco7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc7))
                    .addComponent(Imagem7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCarrinho7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Painel4.setBackground(new java.awt.Color(125, 255, 232));

        txtnome8.setEditable(false);

        txtpreco8.setEditable(false);

        btnCarrinho8.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho8.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho8.setText("+CARRINHO");
        btnCarrinho8.setBorderPainted(false);
        btnCarrinho8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho8ActionPerformed(evt);
            }
        });

        Imagem8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtdesc8.setEditable(false);

        javax.swing.GroupLayout Painel4Layout = new javax.swing.GroupLayout(Painel4);
        Painel4.setLayout(Painel4Layout);
        Painel4Layout.setHorizontalGroup(
            Painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCarrinho8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Imagem8, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpreco8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome8)
                    .addComponent(txtdesc8, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(405, 405, 405))
        );
        Painel4Layout.setVerticalGroup(
            Painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel4Layout.createSequentialGroup()
                .addGroup(Painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel4Layout.createSequentialGroup()
                        .addComponent(txtnome8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtpreco8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc8))
                    .addComponent(Imagem8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCarrinho8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Painel7.setBackground(new java.awt.Color(125, 255, 232));

        txtnome9.setEditable(false);

        txtpreco9.setEditable(false);

        btnCarrinho9.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho9.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho9.setText("+CARRINHO");
        btnCarrinho9.setBorderPainted(false);
        btnCarrinho9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho9ActionPerformed(evt);
            }
        });

        Imagem9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtdesc9.setEditable(false);

        javax.swing.GroupLayout Painel7Layout = new javax.swing.GroupLayout(Painel7);
        Painel7.setLayout(Painel7Layout);
        Painel7Layout.setHorizontalGroup(
            Painel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Painel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCarrinho9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Imagem9, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpreco9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome9)
                    .addComponent(txtdesc9, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(405, 405, 405))
        );
        Painel7Layout.setVerticalGroup(
            Painel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel7Layout.createSequentialGroup()
                .addGroup(Painel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel7Layout.createSequentialGroup()
                        .addComponent(txtnome9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtpreco9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc9))
                    .addComponent(Imagem9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCarrinho9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Painel8.setBackground(new java.awt.Color(125, 255, 232));

        txtnome10.setEditable(false);

        txtpreco10.setEditable(false);

        btnCarrinho10.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho10.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho10.setText("+CARRINHO");
        btnCarrinho10.setBorderPainted(false);
        btnCarrinho10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho10ActionPerformed(evt);
            }
        });

        Imagem10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtdesc10.setEditable(false);

        javax.swing.GroupLayout Painel8Layout = new javax.swing.GroupLayout(Painel8);
        Painel8.setLayout(Painel8Layout);
        Painel8Layout.setHorizontalGroup(
            Painel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Painel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCarrinho10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Imagem10, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpreco10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdesc10, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(404, 404, 404))
        );
        Painel8Layout.setVerticalGroup(
            Painel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel8Layout.createSequentialGroup()
                .addGroup(Painel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel8Layout.createSequentialGroup()
                        .addComponent(txtnome10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtpreco10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc10))
                    .addComponent(Imagem10, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCarrinho10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Painel9.setBackground(new java.awt.Color(125, 255, 232));

        txtnome11.setEditable(false);

        txtpreco11.setEditable(false);

        btnCarrinho11.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrinho11.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho11.setText("+CARRINHO");
        btnCarrinho11.setBorderPainted(false);
        btnCarrinho11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho11ActionPerformed(evt);
            }
        });

        Imagem11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtdesc11.setEditable(false);

        javax.swing.GroupLayout Painel9Layout = new javax.swing.GroupLayout(Painel9);
        Painel9.setLayout(Painel9Layout);
        Painel9Layout.setHorizontalGroup(
            Painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCarrinho11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Imagem11, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpreco11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdesc11, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(404, 404, 404))
        );
        Painel9Layout.setVerticalGroup(
            Painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel9Layout.createSequentialGroup()
                .addGroup(Painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel9Layout.createSequentialGroup()
                        .addComponent(txtnome11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtpreco11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc11))
                    .addComponent(Imagem11, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCarrinho11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtdescricao.setEditable(false);

        txtdesc1.setEditable(false);

        txtdesc2.setEditable(false);

        txtdesc3.setEditable(false);

        txtdesc4.setEditable(false);

        txtdesc5.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Painel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Painel8, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Painel7, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Painel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Painel9, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Imagem0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtNome)
                                                            .addComponent(txtpreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtnome2)
                                                            .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(50, 50, 50))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                                        .addComponent(txtdesc2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Imagem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Imagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnCarrinho3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(btnCarrinho1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Imagem2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                        .addComponent(btnCarrinho2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnome1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnome3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpreco3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdesc1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdesc3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCarrinho4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Imagem4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpreco4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdesc4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCarrinho5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Imagem5, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpreco5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdesc5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtdescricao))
                            .addComponent(Imagem0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtnome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpreco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtdesc1))
                            .addComponent(Imagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarrinho1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Imagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Imagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtnome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpreco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtnome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpreco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarrinho2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarrinho3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Imagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtnome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpreco4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc4))
                    .addComponent(Imagem5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtnome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpreco5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarrinho4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarrinho5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Painel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Painel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel5);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 840, 370));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Descrição:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Título:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Autor:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Editora:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Valor:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        painelImg.setBackground(new java.awt.Color(255, 255, 255));
        painelImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelImg.setPreferredSize(new java.awt.Dimension(138, 188));

        javax.swing.GroupLayout painelImgLayout = new javax.swing.GroupLayout(painelImg);
        painelImg.setLayout(painelImgLayout);
        painelImgLayout.setHorizontalGroup(
            painelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImgLayout.createSequentialGroup()
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelImgLayout.setVerticalGroup(
            painelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImgLayout.createSequentialGroup()
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(painelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        txtDesc.setEditable(false);
        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane2.setViewportView(txtDesc);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 360, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1254, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Compras a = new Compras();
        this.dispose();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Carrinho b = new Carrinho();
        this.dispose();
        b.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Cupons c = new Cupons();
        this.dispose();
        c.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Inicial x = new Inicial();
        this.dispose();
        x.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Conta u = new Conta();
        this.dispose();
        u.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LabelPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelPesquisarMouseClicked
        pesquisarPrincipal();
    }//GEN-LAST:event_LabelPesquisarMouseClicked

    private void TxtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAutorActionPerformed

    private void txtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btnCarrinho7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho7ActionPerformed
        ProdutosCONEC novo = new ProdutosCONEC();
        ArrayList<Produto> lista = novo.listarLivros();
        Carrinho.listanova.add(lista.get(7));
    }//GEN-LAST:event_btnCarrinho7ActionPerformed

    private void btnCarrinho6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho6ActionPerformed
        ProdutosCONEC novo = new ProdutosCONEC();
        ArrayList<Produto> lista = novo.listarLivros();
        Carrinho.listanova.add(lista.get(6));
    }//GEN-LAST:event_btnCarrinho6ActionPerformed

    private void txtprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoActionPerformed

    }//GEN-LAST:event_txtprecoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinhoActionPerformed
        ProdutosCONEC novo = new ProdutosCONEC();
        ArrayList<Produto> lista = novo.listarLivros();
        Carrinho.listanova.add(lista.get(0));

    }//GEN-LAST:event_btnCarrinhoActionPerformed

    private void btnCarrinho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho1ActionPerformed
        ProdutosCONEC novo = new ProdutosCONEC();
        ArrayList<Produto> lista = novo.listarLivros();
        Carrinho.listanova.add(lista.get(1));
    }//GEN-LAST:event_btnCarrinho1ActionPerformed

    private void btnCarrinho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho2ActionPerformed
        ProdutosCONEC novo = new ProdutosCONEC();
        ArrayList<Produto> lista = novo.listarLivros();
        Carrinho.listanova.add(lista.get(2));
    }//GEN-LAST:event_btnCarrinho2ActionPerformed

    private void btnCarrinho5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho5ActionPerformed
        ProdutosCONEC novo = new ProdutosCONEC();
        ArrayList<Produto> lista = novo.listarLivros();
        Carrinho.listanova.add(lista.get(5));
    }//GEN-LAST:event_btnCarrinho5ActionPerformed

    private void btnCarrinho4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho4ActionPerformed
        ProdutosCONEC novo = new ProdutosCONEC();
        ArrayList<Produto> lista = novo.listarLivros();
        Carrinho.listanova.add(lista.get(4));
    }//GEN-LAST:event_btnCarrinho4ActionPerformed

    private void btnCarrinho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho3ActionPerformed
        ProdutosCONEC novo = new ProdutosCONEC();
        ArrayList<Produto> lista = novo.listarLivros();
        Carrinho.listanova.add(lista.get(3));
    }//GEN-LAST:event_btnCarrinho3ActionPerformed

    private void txtnome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnome5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnome5ActionPerformed

    private void txtpreco4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreco4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreco4ActionPerformed

    private void txtnome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnome4ActionPerformed

    private void txtpreco5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreco5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreco5ActionPerformed

    private void txtpreco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreco2ActionPerformed

    private void txtnome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnome2ActionPerformed

    private void txtpreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreco1ActionPerformed

    private void txtnome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnome1ActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnCarrinho8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarrinho8ActionPerformed

    private void btnCarrinho9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarrinho9ActionPerformed

    private void btnCarrinho10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarrinho10ActionPerformed

    private void btnCarrinho11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarrinho11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem0;
    private javax.swing.JLabel Imagem1;
    private javax.swing.JLabel Imagem10;
    private javax.swing.JLabel Imagem11;
    private javax.swing.JLabel Imagem2;
    private javax.swing.JLabel Imagem3;
    private javax.swing.JLabel Imagem4;
    private javax.swing.JLabel Imagem5;
    private javax.swing.JLabel Imagem6;
    private javax.swing.JLabel Imagem7;
    private javax.swing.JLabel Imagem8;
    private javax.swing.JLabel Imagem9;
    private javax.swing.JLabel LabelPesquisar;
    private javax.swing.JPanel Painel1;
    private javax.swing.JPanel Painel2;
    private javax.swing.JPanel Painel4;
    private javax.swing.JPanel Painel7;
    private javax.swing.JPanel Painel8;
    private javax.swing.JPanel Painel9;
    private javax.swing.JTextField TxtAutor;
    private javax.swing.JButton btnCarrinho;
    private javax.swing.JButton btnCarrinho1;
    private javax.swing.JButton btnCarrinho10;
    private javax.swing.JButton btnCarrinho11;
    private javax.swing.JButton btnCarrinho2;
    private javax.swing.JButton btnCarrinho3;
    private javax.swing.JButton btnCarrinho4;
    private javax.swing.JButton btnCarrinho5;
    private javax.swing.JButton btnCarrinho6;
    private javax.swing.JButton btnCarrinho7;
    private javax.swing.JButton btnCarrinho8;
    private javax.swing.JButton btnCarrinho9;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JPanel painelImg;
    private javax.swing.JTextField txtCusto;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtdesc1;
    private javax.swing.JTextField txtdesc10;
    private javax.swing.JTextField txtdesc11;
    private javax.swing.JTextField txtdesc2;
    private javax.swing.JTextField txtdesc3;
    private javax.swing.JTextField txtdesc4;
    private javax.swing.JTextField txtdesc5;
    private javax.swing.JTextField txtdesc6;
    private javax.swing.JTextField txtdesc7;
    private javax.swing.JTextField txtdesc8;
    private javax.swing.JTextField txtdesc9;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtnome1;
    private javax.swing.JTextField txtnome10;
    private javax.swing.JTextField txtnome11;
    private javax.swing.JTextField txtnome2;
    private javax.swing.JTextField txtnome3;
    private javax.swing.JTextField txtnome4;
    private javax.swing.JTextField txtnome5;
    private javax.swing.JTextField txtnome6;
    private javax.swing.JTextField txtnome7;
    private javax.swing.JTextField txtnome8;
    private javax.swing.JTextField txtnome9;
    private javax.swing.JTextField txtpesquisar;
    private javax.swing.JTextField txtpreco;
    private javax.swing.JTextField txtpreco1;
    private javax.swing.JTextField txtpreco10;
    private javax.swing.JTextField txtpreco11;
    private javax.swing.JTextField txtpreco2;
    private javax.swing.JTextField txtpreco3;
    private javax.swing.JTextField txtpreco4;
    private javax.swing.JTextField txtpreco5;
    private javax.swing.JTextField txtpreco6;
    private javax.swing.JTextField txtpreco7;
    private javax.swing.JTextField txtpreco8;
    private javax.swing.JTextField txtpreco9;
    // End of variables declaration//GEN-END:variables

    private void mostrarlivrosnaprincipal(){
        
        try {
            //usa a funcao de listar os livros na Prodostos comprados conec e mostaros na tela
            ProdutosCONEC novo = new ProdutosCONEC();
            
            ArrayList<Produto> lista = novo.listarLivros();
            
            txtNome.setText(lista.get(0).getTitulo());
            txtpreco.setText("R$ "+ Double.toString(lista.get(0).getValor()));
            txtdescricao.setText(lista.get(0).getDescricao());
            ImageIcon icone0 = new ImageIcon(lista.get(0).getImagem());
            icone0.setImage(icone0.getImage().getScaledInstance(Imagem0.getWidth(), Imagem0.getHeight(), 1));
            Imagem0.setIcon(icone0);
            
            txtnome1.setText(lista.get(1).getTitulo());
            txtpreco1.setText("R$ "+ Double.toString(lista.get(1).getValor()));
            txtdesc1.setText(lista.get(1).getDescricao());
            ImageIcon icone1 = new ImageIcon(lista.get(1).getImagem());
            icone1.setImage(icone1.getImage().getScaledInstance(Imagem1.getWidth(), Imagem1.getHeight(), 1));
            Imagem1.setIcon(icone1);
            
            txtnome2.setText(lista.get(2).getTitulo());
            txtpreco2.setText("R$ "+ Double.toString(lista.get(2).getValor()));
            txtdesc2.setText(lista.get(2).getDescricao());
            ImageIcon icone2 = new ImageIcon(lista.get(2).getImagem());
            icone2.setImage(icone2.getImage().getScaledInstance(Imagem2.getWidth(), Imagem2.getHeight(), 1));
            Imagem2.setIcon(icone2);
            
            txtnome3.setText(lista.get(3).getTitulo());
            txtpreco3.setText("R$ "+ Double.toString(lista.get(3).getValor()));
            txtdesc3.setText(lista.get(3).getDescricao());
            ImageIcon icone3 = new ImageIcon(lista.get(3).getImagem());
            icone3.setImage(icone3.getImage().getScaledInstance(Imagem3.getWidth(), Imagem3.getHeight(), 1));
            Imagem3.setIcon(icone3);
            
            txtnome4.setText(lista.get(4).getTitulo());
            txtpreco4.setText("R$ "+ Double.toString(lista.get(4).getValor()));
            txtdesc4.setText(lista.get(4).getDescricao());
            ImageIcon icone4 = new ImageIcon(lista.get(4).getImagem());
            icone4.setImage(icone4.getImage().getScaledInstance(Imagem4.getWidth(), Imagem4.getHeight(), 1));
            Imagem4.setIcon(icone4);
            
            txtnome5.setText(lista.get(5).getTitulo());
            txtpreco5.setText("R$ "+ Double.toString(lista.get(5).getValor()));
            txtdesc5.setText(lista.get(5).getDescricao());
            ImageIcon icone5 = new ImageIcon(lista.get(5).getImagem());
            icone5.setImage(icone5.getImage().getScaledInstance(Imagem5.getWidth(), Imagem5.getHeight(), 1));
            Imagem5.setIcon(icone5);
            
            if(lista.size() >= 7){
                
                txtnome6.setText(lista.get(6).getTitulo());
                txtpreco6.setText("R$ "+ Double.toString(lista.get(6).getValor()));
                txtdesc6.setText(lista.get(6).getDescricao());
                ImageIcon icone6 = new ImageIcon(lista.get(6).getImagem());
                icone6.setImage(icone6.getImage().getScaledInstance(Imagem6.getWidth(), Imagem6.getHeight(), 1));
                Imagem6.setIcon(icone6);
                
                
            }else{
                
                txtnome6.setVisible(false);
                txtpreco6.setVisible(false);
                txtdesc6.setVisible(false);
                btnCarrinho6.setVisible(false);
                Imagem6.setVisible(false);
            }
            
            if(lista.size() >= 8){
                
                txtnome7.setText(lista.get(7).getTitulo());
                txtpreco7.setText("R$ "+ Double.toString(lista.get(7).getValor()));
                txtdesc7.setText(lista.get(7).getDescricao());
                ImageIcon icone7 = new ImageIcon(lista.get(7).getImagem());
                icone7.setImage(icone7.getImage().getScaledInstance(Imagem7.getWidth(), Imagem7.getHeight(), 1));
                Imagem5.setIcon(icone7);
                    
            }else{
                
                txtnome7.setVisible(false);
                txtpreco7.setVisible(false);
                txtdesc7.setVisible(false);
                btnCarrinho7.setVisible(false);
                Imagem7.setVisible(false);
            }
            
            if(lista.size() >= 9){
                
                txtnome8.setText(lista.get(8).getTitulo());
                txtpreco8.setText("R$ "+ Double.toString(lista.get(8).getValor()));
                txtdesc8.setText(lista.get(8).getDescricao());
                ImageIcon icone8 = new ImageIcon(lista.get(8).getImagem());
                icone8.setImage(icone8.getImage().getScaledInstance(Imagem8.getWidth(), Imagem8.getHeight(), 1));
                Imagem8.setIcon(icone8);
                    
            }else{
                
                txtnome8.setVisible(false);
                txtpreco8.setVisible(false);
                txtdesc8.setVisible(false);
                btnCarrinho8.setVisible(false);
                Imagem8.setVisible(false);
            }
            
            if(lista.size() >= 10){
                
                txtnome9.setText(lista.get(9).getTitulo());
                txtpreco9.setText("R$ "+ Double.toString(lista.get(9).getValor()));
                txtdesc9.setText(lista.get(9).getDescricao());
                ImageIcon icone9 = new ImageIcon(lista.get(9).getImagem());
                icone9.setImage(icone9.getImage().getScaledInstance(Imagem9.getWidth(), Imagem9.getHeight(), 1));
                Imagem9.setIcon(icone9);
               
                
            }else{
                
                txtnome9.setVisible(false);
                txtpreco9.setVisible(false);
                txtdesc9.setVisible(false);
                btnCarrinho9.setVisible(false);
                Imagem9.setVisible(false);
                
            }
            
            if(lista.size() >= 11){
                
                txtnome10.setText(lista.get(10).getTitulo());
                txtpreco10.setText("R$ "+ Double.toString(lista.get(10).getValor()));
                txtdesc10.setText(lista.get(10).getDescricao());
                ImageIcon icone10 = new ImageIcon(lista.get(10).getImagem());
                icone10.setImage(icone10.getImage().getScaledInstance(Imagem10.getWidth(), Imagem10.getHeight(), 1));
                Imagem10.setIcon(icone10);
                    
            }else{
                
                txtnome10.setVisible(false);
                txtpreco10.setVisible(false);
                txtdesc10.setVisible(false);
                btnCarrinho10.setVisible(false);
                Imagem10.setVisible(false);
            }
            
            if(lista.size() >= 12){
                
                txtnome11.setText(lista.get(11).getTitulo());
                txtpreco11.setText("R$ "+ Double.toString(lista.get(11).getValor()));
                txtdesc11.setText(lista.get(11).getDescricao());
                ImageIcon icone11 = new ImageIcon(lista.get(11).getImagem());
                icone11.setImage(icone11.getImage().getScaledInstance(Imagem11.getWidth(), Imagem11.getHeight(), 1));
                Imagem11.setIcon(icone11);
                    
            }else{
                
                txtnome11.setVisible(false);
                txtpreco11.setVisible(false);
                txtdesc11.setVisible(false);
                btnCarrinho11.setVisible(false);
                Imagem11.setVisible(false);
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Mostrar livros na principal " + e.getMessage());
            
        }
    }
       private void pesquisarPrincipal(){

        String titulo;
        titulo = txtpesquisar.getText();
        Connection conn;
        //Declara novo objeto para acessar a funçao
        ProdutosCONEC pesquisa = new ProdutosCONEC();
        conn = new Conexao().conectaBD();
        
        //Cria um novo objeto produto que vai receber o retorno da função de consultar
        
        if(conn == null){
            JOptionPane.showMessageDialog(null, "Erro conexao pesquisar");
        }else{
            //Se a conexao foi bem sucedida ele chama a função de consultar
            Produto novo = pesquisa.consultarProds(titulo);

            if (novo == null) {

                JOptionPane.showMessageDialog(null, "Produto não encontrado");

            } else {

                txtTitulo.setText(novo.getTitulo());
                TxtAutor.setText(novo.getAutor());
                txtCusto.setText("R$ " + String.valueOf(novo.getValor()));
                txtEditora.setText(novo.getEditora());
                txtDesc.setText(novo.getDescricao());
                
                ImageIcon icone = new ImageIcon(novo.getImagem());
                icone.setImage(icone.getImage().getScaledInstance(painelImg.getWidth(), painelImg.getHeight(), 1));
                lbImagem.setIcon(icone);
                
            }

        }

    }

}
